(S
  (NP
    (NP (NNP J.P.) (NNP Bolduc))
    (, ,)
    (NP
      (NP (NN vice) (NN chairman))
      (PP
        (IN of)
        (NP
          (NP (NNP W.R.) (NNP Grace) (CC &) (NNP Co.))
          (, ,)
          (SBAR
            (WHNP (WDT which))
            (S
              (VP
                (VBZ holds)
                (NP
                  (NP (DT a) (CD 83.4) (NN %) (NN interest))
                  (PP
                    (IN in)
                    (NP (DT this) (JJ energy-services) (NN company))))))))))
    (, ,))
  (VP (VBD was) (VP (VBN elected) (NP (DT a) (NN director))))
  (. .))
