(S
  (SBAR
    (WHADVP (WRB When))
    (S
      (NP (PRP it))
      (VP
        (VBZ 's)
        (NP
          (NP (NN time))
          (PP (IN for) (NP (PRP$ their) (JJ biannual) (NN powwow)))))))
  (, ,)
  (NP
    (NP (DT the) (NN nation) (POS 's))
    (VBG manufacturing)
    (NNS titans))
  (ADVP (RB typically))
  (VP
    (VBD jet)
    (PRT (RP off))
    (PP
      (TO to)
      (NP
        (NP (DT the) (JJ sunny) (NNS confines))
        (PP (IN of) (NP (NN resort) (NNS towns)))))
    (PP
      (IN like)
      (NP
        (NP (NNP Boca) (NNP Raton))
        (CC and)
        (NP (NNP Hot) (NNP Springs)))))
  (. .))
