(S
  (NP (NNP Clark) (NNP J.) (NNP Vitulli))
  (VP
    (VBD was)
    (VP
      (VBN named)
      (NP
        (NP
          (NP
            (JJ senior)
            (NX
              (NX (NN vice) (NN president))
              (CC and)
              (NX (JJ general) (NN manager))))
          (PP (IN of) (NP (DT this) (NNP U.S.) (NNS sales))))
        (CC and)
        (NP
          (NP (VBG marketing) (NN arm))
          (PP
            (IN of)
            (NP
              (JJ Japanese)
              (NN auto)
              (NN maker)
              (NNP Mazda)
              (NNP Motor)
              (NNP Corp.)))))))
  (. .))
