(S
  (NP (NNP McDermott) (NNP International) (NNP Inc.))
  (VP
    (VBD said)
    (SBAR
      (S
        (NP (PRP$ its) (NNP Babcock) (CC &) (NNP Wilcox) (NN unit))
        (VP
          (VBD completed)
          (NP
            (NP (DT the) (NN sale))
            (PP
              (IN of)
              (NP
                (PRP$ its)
                (NNP Bailey)
                (NNP Controls)
                (NNP Operations))))
          (PP (TO to) (NP (NNP Finmeccanica) (NNP S.p.))))))))
