(S
  (NP (NNP Pacific) (NNP First) (NNP Financial) (NNP Corp.))
  (VP
    (VBD said)
    (SBAR
      (S
        (NP (NNS shareholders))
        (VP
          (VBD approved)
          (NP (PRP$ its) (NN acquisition))
          (PP
            (IN by)
            (NP
              (NP (NNP Royal) (NNP Trustco) (NNP Ltd.))
              (PP (IN of) (NP (NNP Toronto)))))
          (PP
            (IN for)
            (NP
              (NP (NP ($ $) (CD 27)) (NP (DT a) (NN share)))
              (, ,)
              (CC or)
              (NP (QP ($ $) (CD 212) (CD million)))))))))
  (. .))
